[provider]
  name = "python"

[phases.setup]
  nixPkgs = [
    'python38',
    'python38Packages.pip',
    'python38Packages.cryptography',
    'python38Packages.fastapi',
    'python38Packages.uvicorn',
    'python38Packages.pydantic',
    'gcc'
  ]

[phases.build]
  cmds = []

[start]
  cmd = "uvicorn main_improved:app --host 0.0.0.0 --port $PORT"
